modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory
license="${mod_license}"
issueTrackerURL="https://github.com/Bowserinator/create-railgun/issues"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory

logoFile="assets/createrailgun/textures/misc/mod_logo.png"

authors="Bowserinator"
description='''
Adds the railgun from Project Wingman to create
'''

# Uncomment to declare mixins or access transformers
#[[mixins]]
#config="${mod_id}.mixins.json"

#[[accessTransformers]]
#file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="${create_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId = "createbigcannons"
mandatory = true
versionRange = "${cbc_version_range}"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId="sable"
type="optional"
versionRange="[${sable_version_range},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="simulated"
type="optional"
versionRange="[${simulated_version_range},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="aeronautics"
type="optional"
versionRange="[${simulated_version_range},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="offroad"
type="optional"
versionRange="[${simulated_version_range},)"
ordering="NONE"
side="BOTH"